<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Proceed_CallSettings</name>
   <tag></tag>
   <elementGuidId>03db8a14-4eb6-4ffb-8919-720d43791077</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[contains(text(),&quot;Proceed&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>#ffffff</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Ripple__RippleContainer-cs6dy7-0 dXRetU</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope wf-opensans-n4-active wf-opensans-n6-active wf-opensans-n7-active wf-active&quot;]/body[@class=&quot;modal-open&quot;]/div[@class=&quot;fade Modal__StyledModal-sc-1k59v3t-0 dazyR StartConfirmationModal__StyledModal-sc-8227ys-0 gpzFaW modal show&quot;]/div[@class=&quot;modal-dialog modal-sm modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;Footer__StyledFooter-a8p9ar-0 isXRPS StartConfirmationModal___StyledModalFooter-sc-8227ys-36 gkDKxz modal-footer&quot;]/button[@class=&quot;Button__StyledButton-sc-1fz9sxb-0 kHCTVB&quot;]/div[@class=&quot;Ripple__RippleContainer-cs6dy7-0 dXRetU&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//button[2]/div</value>
   </webElementXpaths>
</WebElementEntity>
