<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_TimeZone</name>
   <tag></tag>
   <elementGuidId>501eeda8-2e2e-4ac1-a26f-15f216c076e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='timezoneselection']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>timezone</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>CheckForTimeZone()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>timezoneselection</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select ng-valid ng-not-empty ng-touched ng-dirty ng-valid-parse</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>$parent.teamTimezone</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Australia ( Australian Central Time : +09:30 / +10:30 )  Australia ( Australian Eastern Time : +10:00 / +11:00 )  Bangladesh ( +06:00 )  Brazil( Acre Time: -05:00 )  Brazil( Amazon Time  -04:00 )  Brazil( Brasilia Time  -03:00 )  Brazil( Fernando de Noronha Time -02:00 )  Cambodia ( +07:00 )  Canada( Atlantic Time : -04:00 / -03:00 )  Canada ( Central Time : -06:00 / -05:00 )  Canada ( Eastern Time : -05:00 / -04:00 )  Canada ( Mountain Time : -07:00 / -06:00 )  Canada ( Pacific Time : -08:00 / -07:00 )  China ( +08:00 )  Dubai ( +04:00 )  Egypt ( +02:00 )  France ( +01:00 / +02:00 )  Germany ( +01:00 / +02:00 )  Ghana ( +00:00 )  Hong Kong ( +08:00 )  India (  +05:30 )  Indonesia ( Central Indonesian Time : +08:00 )  Indonesia ( Eastern Indonesian Time : +09:00 )  Indonesia ( Western Indonesian Time : +07:00 )  Iran ( +03:30 / +04:30 )  Ireland ( +00:00 / +01:00 )  Israel ( +02:00 / +03:00 )  Jordan( +02:00 / +03:00 )  Kuwait ( +03:00 )  Malaysia ( +08:00 )  Mexico ( Central Time : -06:00 / -05:00 )  Mexico ( Mountain Time : -07:00 / -06:00 )  Mexico ( Pacific Time : -08:00 / -07:00 )  Myanmar( +06:30 )  Netherlands ( +01:00 / +02:00 )  Nigeria ( +01:00 )  Philippines ( +08:00 )  Qatar ( +03:00 )  Saudi Arabia ( +03:00 )  Senegal ( +00:00 )  Singapore ( +08:00 )  South Africa ( Eastern Africa Time : +03:00 )  South Africa ( South Aftica Standard Time : +02:00 )  Spain ( Central European Time: +01:00 / +02:00 )  Spain ( Western European Time: +00:00 / +01:00 )  Sri Lanka ( +05:30 )  Thailand ( +07:00 )  UAE ( -04:00 )  UK ( +00:00 / +01:00 )  US ( Central Time : -06:00 / -05:00 )  US ( Eastern Time : -05:00 / -04:00 )  US ( Mountain Time : -07:00 / -06:00 )  US ( Pacific Time : -08:00 / -07:00 )  Vietnam ( +07:00 )  Yemen ( +03:00 )  </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;timezoneselection&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//select[@id='timezoneselection']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='left-view']/form/div[2]/div[2]/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time Zone'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Localization'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default Country Code'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='United Kingdom'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//select</value>
   </webElementXpaths>
</WebElementEntity>
