<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>//input[@id='scheduleappointment']</description>
   <name>sheduleappointment</name>
   <tag></tag>
   <elementGuidId>0ab4908a-06ce-4e4a-acff-d43739df01c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='scheduleappointment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
