<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Object</description>
   <name>AssignedTab_object</name>
   <tag></tag>
   <elementGuidId>b7ceb2a0-0d8d-48e5-8df8-f4c6a72ebdcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='AssignedAppointment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
