<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Object</description>
   <name>Close_button_changepassword</name>
   <tag></tag>
   <elementGuidId>d767ea4c-33c8-4072-b3dd-97e2d5adee11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h5[@id='exampleModalLongTitle']//following::i[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
