<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Emailform_profile</description>
   <name>Emailformprofile_object</name>
   <tag></tag>
   <elementGuidId>5116b747-dda7-4711-a7ea-fbd311749055</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='email-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
