<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>obj</description>
   <name>Inquetabobj</name>
   <tag></tag>
   <elementGuidId>e1c65cd5-cd29-47ed-bcb0-2799b7e6ae76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='inQueueAppointment']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
