<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Inque_object</description>
   <name>Inquecount_Object</name>
   <tag></tag>
   <elementGuidId>e734cc5a-3757-4a74-ad15-e5a7ed5b86b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='inQueueAppointment']//span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
