<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Object</description>
   <name>Nameattribute</name>
   <tag></tag>
   <elementGuidId>a853acf0-da92-4dba-b984-b7cca223169f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@title,'Name')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
