<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Object</description>
   <name>Notification_object</name>
   <tag></tag>
   <elementGuidId>3a56c7d9-3925-4c63-a4f6-0a14ce23a8e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='assistNotifier']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
