<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Reports_object</description>
   <name>Reporttab_object</name>
   <tag></tag>
   <elementGuidId>f9841f73-28eb-4b10-8df6-00196ccff555</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='Reports']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
