<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Schedulebutton</description>
   <name>Schedulebutton_ap_popup</name>
   <tag></tag>
   <elementGuidId>28f043bb-2cd1-490c-80ae-32e63e65158c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@ng-click='createAppointment()']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
