<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Object</description>
   <name>Teams_Tab_Object</name>
   <tag></tag>
   <elementGuidId>4b69cd5c-a9a8-477c-82a7-4e1c22437c9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='Team']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
