<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select a team to view detailsPlease sel_21f0a7</name>
   <tag></tag>
   <elementGuidId>e33e62fa-bf0f-48ce-aa36-f591f5cca93c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='myTabContent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab-content team-management-view-content</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>myTabContent</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select a team to view detailsPlease select a team from the left panel to viewmembers, page design and settingsTeam Name :   person_add Add a New Memberclose*All field are compulsorySelect Role CANCEL ADDSearch:NameEmail IDPhoneRoleNo data available in tableShowing 0 to 0 of 0 entriesPreviousNextTeam Name :   GeneralNotificationFeedbackLocalizationTime ZoneMismatch between selected time zone and browser time zone. Match browser time?Default Country CodeCase SettingArchiving  Geo Location  Reset SAVECustomise email and sms body to give a personalized experience to your customerEmail TemplateEmail Header *Choose file...Example invalid custom file feedbackUPLOADFile Size : 2MB, Dimension 00px X 00pxEmail Footer *Choose file...Example invalid custom file feedbackUPLOADFile Size : 2MB, Dimension 00px X 00pxSender's Email * Please enter a valid email address (name@mail.com)Subject Line * Character Remaining : 64Email Body *Character Remaining : 612SMS TemplateSMS Body *Character Remaining : 612Reset SAVEHi Suman !Note: For Android use Chrome &amp; for IOS use Safari (11+) for better experienceVideo Call Link : https://url.comCustomise feedback from your customer based on your requirementsMax 2 questions allowed.Question 1 This is a default question &amp; cannot be customized.Star Rating Question, 5 scaleSaveFeedbackstar_borderstar_borderstar_borderstar_borderstar_borderSubmitChoose a team to view details orCreate a New TeamChoose a team to view details orCreate a New TeamTeam Name : App LandingOnboardingVideo Call InterfaceLink ExpiryPreviewclose SEND TEST EMAILSEND TEST SMSOnboarding https://previewtestonboardingAdd brand colour, logo, tagline and description to create your own branding.Brand Colour Font ColourBlack (#4a4a4a)White (#ffffff)To be used for landing page and other backgroundsFontSelect Font To be used for the entire customer appBrand LogoChoose file...EbrandLogoFilexample invalid custom file feedbackUPLOADFile Size : 2MBApp Tagline Character Remaining : 30App DescriptionCharacter Remaining : 110Reset SAVECustomise button and labels to match your brand identityButton Colour Button Label Character Remaining : 20To be used on the onboarding screen as a label on the buttonReset SAVEChoose your audio &amp; video settings for the appointmentvideocam micCustomise your app interface based on your customer needsAddress Support Person by Character Remaining : 20Assign a desired name for your support person, this name will be replaced wherever the word “Support Person&quot; is used.Video on focusCustomerAgent.Selecting the desired video will make it appear on the main video frame at Customer’s end.Reset SAVE Customer’s Video's Video 's VideoCustomer's VideoConnecting to Customise your appointment link expiry pageDescription *Character Remaining : 200 Add contact infoPhone Add another phonePhone Invalid PhoneEmail Invalid Email Add another emailEmail Invalid EmailReset SAVElink_offAppointment Link Expiredphoneemail</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myTabContent&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='myTabContent']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[2]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page Design'])[1]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ui-view/div/div/div[2]/div/div</value>
   </webElementXpaths>
</WebElementEntity>
