<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Settingstab</description>
   <name>Settingsmousehover</name>
   <tag></tag>
   <elementGuidId>8d2a5500-6ccc-476f-b7b4-c384222c89f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='Settings']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
