<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>UiObject</description>
   <name>Tagnamcreationpopup</name>
   <tag></tag>
   <elementGuidId>e1242a95-b9cd-4177-8161-836b79370349</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='create-tags-modal']//div[@class='modal-content']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
