<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Appointmentcreationpopupobject</description>
   <name>Appointmentcreationpopup</name>
   <tag></tag>
   <elementGuidId>bfbb5207-55cd-46d5-bfa0-f88cc32a22bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='appointmentCreation']//div[@class='modal-content']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
