<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Customersearchfieldunderpopup</description>
   <name>Customersearchfieldunderpopup</name>
   <tag></tag>
   <elementGuidId>5e66ea17-ea2e-4408-8768-7f1858f86107</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customerSearchInput']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
