<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Noresultfoundobjectvalue</description>
   <name>Noresultfoundobject</name>
   <tag></tag>
   <elementGuidId>d449ef73-9dd7-4f73-a828-8bd867aa29e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='imiassist-search-dropdown__no-results']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
