<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Scheduleanappointmentfilterobject</description>
   <name>Scheduleanappointmentfilterobject</name>
   <tag></tag>
   <elementGuidId>26e0699b-1b44-4425-a13a-a89e317e9b00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='All']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
