<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Searchfilterwithemailobject</description>
   <name>Searchfilterwithemailobject</name>
   <tag></tag>
   <elementGuidId>0293c64b-2b4a-4dd5-ac95-c11988b5b16e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[contains(text(),'Email')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
