<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>//div[@id='assistNotifier']</description>
   <name>smsconfirmationnotifier</name>
   <tag></tag>
   <elementGuidId>6ed78629-7957-4ed5-87e1-5c59776ecd13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='assistNotifier']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
