<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Appointmentconfirmationpopup</description>
   <name>Appointmentconfirmationpopup</name>
   <tag></tag>
   <elementGuidId>20504159-fdc0-418f-a892-4053e1542d66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='appointmentCreatedModal']//div[@class='modal-content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
