<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Please select an agent to assign an app_67686a (1)</name>
   <tag></tag>
   <elementGuidId>92bfe76e-d624-4b23-bdbd-d4932dffaf3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='assignAppointmentModal']/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Please select an agent to assign an appointment to         qateam   keyboard_arrow_down        mail check        devteam   keyboard_arrow_down        mail check        Team 234   keyboard_arrow_down        Bharath gedela    rishita        FieldTest   keyboard_arrow_down        Abhinav singh    Abhinav Singh    anvesh    ashutosh singh    Bharath gedela    Download buddy    Haneef Mansoor    Jon Doe    katarzyna W    Madhuri K    Mrudul Nekkanti    neha g    pooja    Rafi Shaik    RafiQa Shaik    rishita    Rocking theja    samaritha    Samaritha    Shyamsundar Reddy    srikanth Brahmanapalli    sumeetha    Test qa    Testuser2 sirname    Uday Kiran    uday kiran        another falakura   keyboard_arrow_down        Bharath gedela        Testing12334   keyboard_arrow_down        rishita    Samaritha        testing team   keyboard_arrow_down        sumeetha        ssss   keyboard_arrow_down        Download buddy        Qastg   keyboard_arrow_down        june test fs    Rafi Shaik    RafiQa Shaik    Rafistgtest sh    random m    Test qa    TSET GUI        Rafiqastg   keyboard_arrow_down        Rafi Shaik    RafiQa Shaik    TSET GUI        UnderRafistgtestdepartment   keyboard_arrow_down        Rafi Shaik    Rafistgtest sh        team   keyboard_arrow_down        Rafi Shaik        abhinav team   keyboard_arrow_down        Abhinav Singh        Team1   keyboard_arrow_down        neha g    rishita        qat   keyboard_arrow_down        june test fs    Rafi Shaik        Teamde   keyboard_arrow_down        Rafi Shaik        Rafi   keyboard_arrow_down       Rafitestp shaiktestpp   remove_circle_outline         testonwebpack   keyboard_arrow_down        Rafitestp shaiktestpp        amtest   keyboard_arrow_down        Rafitestp shaiktestpp           </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;assignAppointmentModal&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='assignAppointmentModal']/div/div/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assign'])[1]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APPLY FILTER'])[2]/following::div[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ui-view/div[2]/div/div/div[2]</value>
   </webElementXpaths>
</WebElementEntity>
